"""
Django settings for presence_site project.

Generated by 'django-admin startproject' using Django 5.2.14.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
import subprocess
from pathlib import Path

from django.contrib.messages import constants as message_constants

# Map Django's message levels onto Bootstrap's alert suffixes (error→danger)
# so base.html can build `alert-<tag>` classes directly.
MESSAGE_TAGS = {message_constants.ERROR: "danger"}

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = (
    os.environ.get("DJANGO_SECRET_KEY")
    or "django-insecure-!g30%)$1folu5c(=!8fz05tik^3pl+as8xrs28&-j&$5@7owk&"
)

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get("DJANGO_DEBUG", "True").strip().lower() in {"1", "true", "yes", "on"}

ALLOWED_HOSTS = [
    h.strip()
    for h in os.environ.get("DJANGO_ALLOWED_HOSTS", "").split(",")
    if h.strip()
]

# Origins trusted for unsafe (POST/PUT/...) requests. Django 4.0+ requires the
# scheme, and an HTTPS origin must be listed explicitly here even if its host is
# already in ALLOWED_HOSTS — otherwise the admin login POST fails with
# "Origin checking failed ... does not match any trusted origins".
CSRF_TRUSTED_ORIGINS = [
    o.strip()
    for o in os.environ.get("DJANGO_CSRF_TRUSTED_ORIGINS", "").split(",")
    if o.strip()
]

# Caddy terminates TLS and reverse-proxies plain HTTP to this app, so without
# this Django thinks every request is insecure: is_secure() is False, the CSRF
# origin check expects http:// (mismatching the browser's https:// Origin), and
# secure cookies/redirects misbehave. Caddy sends X-Forwarded-Proto by default.
SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")

# Application version shown on the About modal.
#
# Built images set the VERSION env var at build time (Dockerfile ARG/ENV), and
# that always wins. When it is unset/blank — i.e. a local source checkout, e.g.
# `runserver` — fall back to resolving it from git the same way CI does: an exact
# tag if HEAD is tagged, else the short commit SHA. If git is unavailable (no
# binary, no .git, shallow clone with no tag) the value is "dev".
def _version_from_git() -> str:
    def _git(*args: str) -> str | None:
        try:
            result = subprocess.run(
                ["git", *args],
                cwd=BASE_DIR,
                capture_output=True,
                text=True,
                timeout=5,
            )
        except (OSError, subprocess.SubprocessError):
            return None
        if result.returncode != 0:
            return None
        return result.stdout.strip() or None

    return (
        _git("describe", "--tags", "--exact-match")
        or _git("rev-parse", "--short", "HEAD")
        or "dev"
    )


VERSION = os.environ.get("VERSION", "").strip() or _version_from_git()


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "presence",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "presence_site.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
                "presence.context_processors.version",
            ],
        },
    },
]

WSGI_APPLICATION = "presence_site.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": os.environ.get("PRESENCE_DB_PATH") or (BASE_DIR / "db.sqlite3"),
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

LOGIN_URL = "login"
LOGIN_REDIRECT_URL = "index"
LOGOUT_REDIRECT_URL = "login"

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = "static/"
STATIC_ROOT = BASE_DIR / "staticfiles"
# WhiteNoise's manifest storage hashes filenames for far-future caching, but it
# requires `collectstatic` to have populated STATIC_ROOT (see entrypoint.sh's
# gunicorn path). That makes it unsuitable for `runserver`, so fall back to the
# plain storage when DEBUG is on. The test suite (DEBUG off) overrides this to
# the plain storage too — see presence/tests/conftest.py.
STORAGES = {
    "default": {"BACKEND": "django.core.files.storage.FileSystemStorage"},
    "staticfiles": {
        "BACKEND": (
            "django.contrib.staticfiles.storage.StaticFilesStorage"
            if DEBUG
            else "whitenoise.storage.CompressedManifestStaticFilesStorage"
        )
    },
}

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"
