"""
Django settings for presence_site project.

Generated by 'django-admin startproject' using Django 5.2.14.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
import subprocess
from pathlib import Path

from django.contrib.messages import constants as message_constants
from django.core.exceptions import ImproperlyConfigured

# Map Django's message levels onto Bootstrap's alert suffixes (error→danger)
# so base.html can build `alert-<tag>` classes directly.
MESSAGE_TAGS = {message_constants.ERROR: "danger"}

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# --- Secure-by-default configuration helpers -----------------------------
#
# These pure helpers read from an explicit environment mapping (not os.environ
# directly) so they can be unit-tested without process-global state. The values
# applied below are the production defaults; DEBUG must be opted into and the
# secret key is mandatory unless DEBUG is on.

_TRUE_VALUES = {"1", "true", "yes", "on"}

# The throwaway key used only when DEBUG is on. It is prefixed with
# "django-insecure-" so Django's own deploy check flags it if it ever leaks
# into a production (DEBUG off) process — which resolve_secret_key forbids.
DEV_SECRET_KEY = (
    "django-insecure-!g30%)$1folu5c(=!8fz05tik^3pl+as8xrs28&-j&$5@7owk&"
)


def env_bool(environ: dict, name: str, *, default: bool) -> bool:
    """Interpret an environment variable as a boolean.

    A missing variable returns ``default``; any present value is truthy only
    when it is one of ``_TRUE_VALUES`` (case-insensitive, whitespace-trimmed).
    """
    raw = environ.get(name)
    if raw is None:
        return default
    return raw.strip().lower() in _TRUE_VALUES


def resolve_debug(environ: dict) -> bool:
    """Return DEBUG, defaulting to OFF so deployments fail safe (#1)."""
    return env_bool(environ, "DJANGO_DEBUG", default=False)


def resolve_secret_key(environ: dict, *, debug: bool) -> str:
    """Return the secret key, failing closed in production (#2).

    A non-blank ``DJANGO_SECRET_KEY`` always wins. When it is unset/blank the
    insecure dev key is allowed only with DEBUG on; otherwise we raise rather
    than silently run with a publicly known key.
    """
    key = (environ.get("DJANGO_SECRET_KEY") or "").strip()
    if key:
        return key
    if debug:
        return DEV_SECRET_KEY
    raise ImproperlyConfigured(
        "DJANGO_SECRET_KEY must be set when DJANGO_DEBUG is off. Generate one "
        "with: python -c \"from django.core.management.utils import "
        'get_random_secret_key; print(get_random_secret_key())"'
    )


def security_overrides(debug: bool) -> dict:
    """HTTPS cookie/redirect/HSTS hardening, applied whenever DEBUG is off (#5).

    Safe behind the TLS-terminating Caddy proxy because SECURE_PROXY_SSL_HEADER
    (below) makes ``request.is_secure()`` true, so SECURE_SSL_REDIRECT does not
    loop. In DEBUG (plain-HTTP local dev) everything is relaxed.
    """
    if debug:
        return {
            "SESSION_COOKIE_SECURE": False,
            "CSRF_COOKIE_SECURE": False,
            "SECURE_SSL_REDIRECT": False,
            "SECURE_HSTS_SECONDS": 0,
            "SECURE_HSTS_INCLUDE_SUBDOMAINS": False,
            "SECURE_HSTS_PRELOAD": False,
        }
    return {
        "SESSION_COOKIE_SECURE": True,
        "CSRF_COOKIE_SECURE": True,
        "SECURE_SSL_REDIRECT": True,
        "SECURE_HSTS_SECONDS": 31536000,  # 1 year
        "SECURE_HSTS_INCLUDE_SUBDOMAINS": True,
        "SECURE_HSTS_PRELOAD": True,
    }


# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = resolve_debug(os.environ)

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = resolve_secret_key(os.environ, debug=DEBUG)

ALLOWED_HOSTS = [
    h.strip()
    for h in os.environ.get("DJANGO_ALLOWED_HOSTS", "").split(",")
    if h.strip()
]

# What3Words REST API key (issue #54). Optional: only needed to enter a
# location position as a three-word address; without it the form still
# accepts decimal lat,lon pairs and explains why W3W input is refused.
W3W_API_KEY = os.environ.get("W3W_API_KEY", "").strip()

# Origins trusted for unsafe (POST/PUT/...) requests. Django 4.0+ requires the
# scheme, and an HTTPS origin must be listed explicitly here even if its host is
# already in ALLOWED_HOSTS — otherwise the admin login POST fails with
# "Origin checking failed ... does not match any trusted origins".
CSRF_TRUSTED_ORIGINS = [
    o.strip()
    for o in os.environ.get("DJANGO_CSRF_TRUSTED_ORIGINS", "").split(",")
    if o.strip()
]

# Caddy terminates TLS and reverse-proxies plain HTTP to this app, so without
# this Django thinks every request is insecure: is_secure() is False, the CSRF
# origin check expects http:// (mismatching the browser's https:// Origin), and
# secure cookies/redirects misbehave. Caddy sends X-Forwarded-Proto by default.
SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")

# HTTPS hardening (secure cookies, SSL redirect, HSTS) — on in production,
# relaxed under DEBUG. See security_overrides() above for the rationale.
for _setting_name, _setting_value in security_overrides(DEBUG).items():
    globals()[_setting_name] = _setting_value

# Application version shown on the About modal.
#
# Built images set the VERSION env var at build time (Dockerfile ARG/ENV), and
# that always wins. When it is unset/blank — i.e. a local source checkout, e.g.
# `runserver` — fall back to resolving it from git the same way CI does: an exact
# tag if HEAD is tagged, else the short commit SHA. If git is unavailable (no
# binary, no .git, shallow clone with no tag) the value is "dev".
def _version_from_git() -> str:
    def _git(*args: str) -> str | None:
        try:
            result = subprocess.run(
                ["git", *args],
                cwd=BASE_DIR,
                capture_output=True,
                text=True,
                timeout=5,
            )
        except (OSError, subprocess.SubprocessError):
            return None
        if result.returncode != 0:
            return None
        return result.stdout.strip() or None

    return (
        _git("describe", "--tags", "--exact-match")
        or _git("rev-parse", "--short", "HEAD")
        or "dev"
    )


VERSION = os.environ.get("VERSION", "").strip() or _version_from_git()


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "presence",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "presence_site.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
                "presence.context_processors.version",
            ],
        },
    },
]

WSGI_APPLICATION = "presence_site.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": os.environ.get("PRESENCE_DB_PATH") or (BASE_DIR / "db.sqlite3"),
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

LOGIN_URL = "login"
LOGIN_REDIRECT_URL = "index"
LOGOUT_REDIRECT_URL = "login"

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = "static/"
STATIC_ROOT = BASE_DIR / "staticfiles"
# WhiteNoise's manifest storage hashes filenames for far-future caching, but it
# requires `collectstatic` to have populated STATIC_ROOT (see entrypoint.sh's
# gunicorn path). That makes it unsuitable for `runserver`, so fall back to the
# plain storage when DEBUG is on. The test suite (DEBUG off) overrides this to
# the plain storage too — see presence/tests/conftest.py.
STORAGES = {
    "default": {"BACKEND": "django.core.files.storage.FileSystemStorage"},
    "staticfiles": {
        "BACKEND": (
            "django.contrib.staticfiles.storage.StaticFilesStorage"
            if DEBUG
            else "whitenoise.storage.CompressedManifestStaticFilesStorage"
        )
    },
}

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"
