# Generated by Django 5.2.14 on 2026-05-10 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Presence",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=64, unique=True)),
                ("enabled", models.BooleanField(default=True)),
                ("min_on_duration", models.DurationField()),
                ("max_on_duration", models.DurationField()),
                ("min_off_duration", models.DurationField()),
                ("max_off_duration", models.DurationField()),
                (
                    "earliest_on",
                    models.TimeField(
                        help_text="Wall-clock time of day at which the window opens."
                    ),
                ),
                (
                    "latest_off",
                    models.TimeField(
                        help_text="Wall-clock time of day at which the window closes. If <= earliest_on, the window wraps past midnight."
                    ),
                ),
                (
                    "current_state",
                    models.CharField(
                        choices=[("on", "on"), ("off", "off")],
                        default="off",
                        max_length=3,
                    ),
                ),
                ("state_since", models.DateTimeField(blank=True, null=True)),
                ("next_transition_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name_plural": "Presences",
            },
        ),
    ]
