# Generated by Django 5.2.14 on 2026-05-10 18:50

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("presence", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="presence",
            name="max_off_duration",
            field=models.DurationField(
                validators=[
                    django.core.validators.MinValueValidator(
                        datetime.timedelta(seconds=60)
                    )
                ]
            ),
        ),
        migrations.AlterField(
            model_name="presence",
            name="max_on_duration",
            field=models.DurationField(
                validators=[
                    django.core.validators.MinValueValidator(
                        datetime.timedelta(seconds=60)
                    )
                ]
            ),
        ),
        migrations.AlterField(
            model_name="presence",
            name="min_off_duration",
            field=models.DurationField(
                validators=[
                    django.core.validators.MinValueValidator(
                        datetime.timedelta(seconds=60)
                    )
                ]
            ),
        ),
        migrations.AlterField(
            model_name="presence",
            name="min_on_duration",
            field=models.DurationField(
                validators=[
                    django.core.validators.MinValueValidator(
                        datetime.timedelta(seconds=60)
                    )
                ]
            ),
        ),
    ]
