# Generated by Django 5.2.14 on 2026-05-10 20:50

import presence.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("presence", "0002_alter_presence_max_off_duration_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="presence",
            name="timezone",
            field=models.CharField(
                default="Europe/London",
                help_text="IANA timezone name (e.g. Europe/London) that the window times are interpreted in.",
                max_length=64,
                validators=[presence.models.validate_iana_timezone],
            ),
            preserve_default=False,
        ),
    ]
