# Generated by Django 6.0.5 on 2026-05-11 10:46

import presence.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("presence", "0003_presence_timezone"),
    ]

    operations = [
        migrations.AddField(
            model_name="presence",
            name="city",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Name of a city from astral's built-in database. Required when either window edge is solar-relative.",
                max_length=64,
                validators=[presence.models.validate_astral_city],
            ),
        ),
        migrations.AddField(
            model_name="presence",
            name="earliest_on_offset",
            field=models.DurationField(
                blank=True,
                help_text="Signed offset from sunset, e.g. -1:00:00 for one hour before sunset. Required when 'earliest on relative to sunset' is checked.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="presence",
            name="earliest_on_relative_to_sunset",
            field=models.BooleanField(
                default=False,
                help_text="If set, the window opens at sunset + earliest_on_offset (offset may be negative).",
            ),
        ),
        migrations.AddField(
            model_name="presence",
            name="latest_off_offset",
            field=models.DurationField(
                blank=True,
                help_text="Signed offset from sunrise, e.g. 2:00:00 for two hours after sunrise. Required when 'latest off relative to sunrise' is checked.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="presence",
            name="latest_off_relative_to_sunrise",
            field=models.BooleanField(
                default=False,
                help_text="If set, the window closes at sunrise + latest_off_offset (offset may be negative).",
            ),
        ),
        migrations.AlterField(
            model_name="presence",
            name="earliest_on",
            field=models.TimeField(
                blank=True,
                help_text="Wall-clock time of day when the window opens. Leave blank when 'earliest on relative to sunset' is checked.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="presence",
            name="latest_off",
            field=models.TimeField(
                blank=True,
                help_text="Wall-clock time of day when the window closes. Leave blank when 'latest off relative to sunrise' is checked. If <= earliest_on, the window wraps past midnight.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="presence",
            name="timezone",
            field=models.CharField(
                help_text="IANA timezone name (e.g. Europe/London) that the wall-clock window times are interpreted in.",
                max_length=64,
                validators=[presence.models.validate_iana_timezone],
            ),
        ),
    ]
