# Generated by Django 6.0.5 on 2026-05-12 11:28

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("presence", "0005_presence_identifier"),
    ]

    operations = [
        migrations.AlterField(
            model_name="presence",
            name="max_off_duration",
            field=models.DurationField(
                help_text="Clock-style duration HH:MM:SS, e.g. 00:45:00 for 45 minutes. Must be >= min_off_duration.",
                validators=[
                    django.core.validators.MinValueValidator(
                        datetime.timedelta(seconds=60)
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="presence",
            name="max_on_duration",
            field=models.DurationField(
                help_text="Clock-style duration HH:MM:SS, e.g. 02:00:00 for 2 hours. Must be >= min_on_duration.",
                validators=[
                    django.core.validators.MinValueValidator(
                        datetime.timedelta(seconds=60)
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="presence",
            name="min_off_duration",
            field=models.DurationField(
                help_text="Clock-style duration HH:MM:SS, e.g. 00:05:00 for 5 minutes. Minimum 1 minute.",
                validators=[
                    django.core.validators.MinValueValidator(
                        datetime.timedelta(seconds=60)
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="presence",
            name="min_on_duration",
            field=models.DurationField(
                help_text="Clock-style duration HH:MM:SS, e.g. 00:01:30 for 1 min 30 sec, 01:00:00 for 1 hour. Minimum 1 minute.",
                validators=[
                    django.core.validators.MinValueValidator(
                        datetime.timedelta(seconds=60)
                    )
                ],
            ),
        ),
    ]
