# Generated by Django 6.0.5 on 2026-05-13 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("presence", "0006_alter_presence_max_off_duration_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="presence",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                help_text="When this row was first saved. Stored and shown in UTC.",
            ),
        ),
        migrations.AlterField(
            model_name="presence",
            name="current_state",
            field=models.CharField(
                choices=[("on", "on"), ("off", "off")],
                default="off",
                help_text="Live on/off state, maintained by the background runner. Read-only; manual edits will be overwritten on the next tick.",
                max_length=3,
            ),
        ),
        migrations.AlterField(
            model_name="presence",
            name="enabled",
            field=models.BooleanField(
                default=True,
                help_text="Uncheck to pause this row without deleting it. The runner thread skips disabled rows and stops mutating their state.",
            ),
        ),
        migrations.AlterField(
            model_name="presence",
            name="name",
            field=models.CharField(
                help_text="Human-readable label shown in the admin. Must be unique.",
                max_length=64,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="presence",
            name="next_transition_at",
            field=models.DateTimeField(
                blank=True,
                help_text="Scheduled time of the next on/off flip. Stored in UTC; the admin renders it in the row's timezone.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="presence",
            name="state_since",
            field=models.DateTimeField(
                blank=True,
                help_text="When the current state was entered. Stored in UTC; the admin renders it in the row's timezone.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="presence",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True,
                help_text="When this row was last saved. Stored and shown in UTC.",
            ),
        ),
    ]
