# Generated by Django 6.0.5 on 2026-05-13 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("presence", "0007_alter_presence_created_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="presence",
            name="name",
            field=models.CharField(
                help_text="Human-readable label shown in the admin. Not required to be unique; the `identifier` field is the unique key.",
                max_length=64,
            ),
        ),
    ]
