# Generated by Django 6.0.5 on 2026-06-27 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("presence", "0009_access_key"),
    ]

    operations = [
        migrations.AddField(
            model_name="accesskey",
            name="last_generated_at",
            field=models.DateTimeField(
                blank=True,
                default=None,
                help_text="When this key's value was last regenerated. Null for keys that have never been regenerated. Stored and shown in UTC.",
                null=True,
            ),
        ),
    ]
