# Generated by Django 6.0.5 on 2026-06-28 14:28

import presence.models
from django.db import migrations, models


def copy_timezone_city_to_location(apps, schema_editor):
    """Seed each Location's timezone/city from one of its presences.

    Issue #43 assumes every presence in a location already shares the same
    timezone/city, so the first presence found supplies the location's values.
    Locations with no presences keep the field default (``UTC`` / blank). Runs
    after the Location columns are added but before the Presence columns are
    deprecated, while the source values are still populated.
    """
    Location = apps.get_model("presence", "Location")
    for location in Location.objects.all():
        presence = location.presences.first()
        if presence is None:
            continue
        location.timezone = presence.timezone or "UTC"
        location.city = presence.city or ""
        location.save(update_fields=["timezone", "city"])


class Migration(migrations.Migration):

    dependencies = [
        ("presence", "0011_location"),
    ]

    operations = [
        migrations.AddField(
            model_name="location",
            name="city",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Name of a city from astral's built-in database. Required when a presence at this location uses a solar-relative window edge.",
                max_length=64,
                validators=[presence.models.validate_astral_city],
            ),
        ),
        migrations.AddField(
            model_name="location",
            name="timezone",
            field=models.CharField(
                default="UTC",
                help_text="IANA timezone name (e.g. Europe/London) that the wall-clock window times of presences at this location are interpreted in.",
                max_length=64,
                validators=[presence.models.validate_iana_timezone],
            ),
        ),
        migrations.RunPython(
            copy_timezone_city_to_location, migrations.RunPython.noop
        ),
        migrations.AlterField(
            model_name="presence",
            name="city",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Deprecated (issue #43): the city now lives on the presence's Location and this field is no longer used.",
                max_length=64,
            ),
        ),
        migrations.AlterField(
            model_name="presence",
            name="timezone",
            field=models.CharField(
                blank=True,
                default=None,
                help_text="Deprecated (issue #43): the timezone now lives on the presence's Location and this field is no longer used.",
                max_length=64,
                null=True,
            ),
        ),
    ]
