# Generated by Django 6.0.5 on 2026-07-04 19:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("presence", "0012_move_timezone_city_to_location"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="presence",
            name="city",
        ),
        migrations.RemoveField(
            model_name="presence",
            name="timezone",
        ),
    ]
