# Generated by Django 6.0.5 on 2026-07-04 20:20

import presence.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("presence", "0013_remove_presence_city_remove_presence_timezone"),
    ]

    operations = [
        migrations.AddField(
            model_name="location",
            name="position",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Optional decimal 'lat,lon' pair (e.g. 51.520847,-0.195521). When set, the map places this location here instead of at its city. The edit form also accepts a What3Words address (///word.word.word), stored converted to lat/lon.",
                max_length=64,
                validators=[presence.models.validate_lat_lon],
            ),
        ),
    ]
