# Generated by Django 6.0.5 on 2026-07-04 22:48

import presence.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("presence", "0014_location_position"),
    ]

    operations = [
        migrations.AlterField(
            model_name="location",
            name="position",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Optional 'lat,lon' pair, as decimals (e.g. 51.520847,-0.195521) or degrees with N/S/E/W (e.g. 36.35702° N, 5.24036° W). When set, the map places this location here instead of at its city. The edit form also accepts a What3Words address (///word.word.word); all forms are stored as the decimal pair.",
                max_length=64,
                validators=[presence.models.validate_lat_lon],
            ),
        ),
    ]
